let situation = [
    "Get divorced. For added fun, don't move either spouse out.",
    "Bankruptcy, delete all but $200",
    "Have the biggest house fire that you can manage.",
    "Sick day: have one of your Sims take a day off from work/school",
    "Adopt a child",
    "Sim has an affair",
    "Unemployment, everyone loses their job, and has to pick a different career path",
    "Move to a new house.",
    "Redecorate a room in your house based on a theme",
    "Midlife Crisis, blow all money on entertainment, clothes, cars",
    "Throw a party!",
    "Have family dance together.",
    "Give one of your sims a new hair style and colour!",
    "Adopt an infant",
    "Have twins or adopt two infants.",
    "Teen or child: Sneak out with a friend/skip school with a friend",
    "Pick a sim in the house to be enemies with all other sims in the house",
    "Married with children: Have adult sims make out in front of their kids.",
    "Teen: Go steady with another teen. Then cheat on that sim",
    "Teen: Get a job and NEVER go to work.",
    "Visit a community lot and pick a fight with everyone you can.",
    "Pick a community lot you haven't visited in awhile and take the family on an outing",
    "Kick tombstones. Try to make ghosts mad. Break an Urn",
    "Teen:go on a date",
    "Have a pool party.",
    "Try to have all sims eat breakfast, lunch, or dinner together.",
    "Spend the week eating only from the buffet table.",
    "Kill a sim by cowplant. Or some other method. Who cares, just kill someone!",
    "Club: Call to join, then be rude to the club people. Prank them, poke, fight them. Try to make them hate you.",
    "Pick a sim with the least creativity skill and have them play for tips.",
    "Go to a community lot and play in a band for tips.",
    "Throw the worst possible party.",
    "Be a personal trainer.",
    "Get into a secret club. Then do the wacky shake with everyone you run into.",
    "Start your own club",
    "Go on a date",
    "Woohoo not in a bed",
    "While on a date, use the karaoke machine.",
    "Open a business or close yours down",
    "Go to a restaurant and be mean to the waitstaff",
    "Create a custom painting.",
    "add about 12 trees or plants to your lot",
    "Shoot off fountain fireworks until they blow up in your sims face.",
    "Pick a holiday and decorate the house as if it were that holiday.",
    "Set off lots and lots of fireworks. (wall crackers, floor fireworks and sparklers)",
    "Put jewelry on a sim/change a sims jewelry",
    "Have a party while on vacation.",
    "Find a new spouse while on vacation.",
    "Go on vacation and stay in the worst lot",
    "Give someone a massage.",
    "Get a massage.",
    "Invite a guest on vacation.",
    "Try for a baby",
    "Give everyone in your household short hair or long hair, opposite of whatever they had before.",
    "Invite a sim to move into your current household",
    "Go buy books and food and anything you can buy in a store",
    "Drafted: force one of your sims to join the military career.",
    "Duel: Fight another sim",
    "Robbery: Use testingcheatsenabled cheat then shift+click the mailbox and one of the options should invite over a robber.",
    "Picnic: Cook a meal, then take it to a park to eat.",
    "Have a sim write a book.",
    "Baby daddy: Have your male sim go and get another sim pregnant, if you only have a female sim do the same but vice versa",
    "Goth phase: dress one of your sims entirely in black with black makeup",
    "Create a Sim from your favorite TV show and move them into your town",
    "Go on vacation",
    "Bank robber: Use the family funds cheat to put your money at Zero",
    "Change one of your Sims skins to any shade of blue",
    "I has chezburger? If you have sims pets adopt a cat. If you don't then take your household and eat out",
    "Red is the new black: Make a sim of your choice dress only in red clothing",
    "Have your couple or any couple in your household have a big fight",
    "Put makeup on all your male sims.",
    "Delete the furniture in one room and redecorate it as a different room in the house. Example: living room turns into bedroom.",
    "Have a male or female sim have the baby of the UGLIEST sim you can find in town",
    "Needs boost: Use cheats to bring your Sims needs up to full",
    "Make one sim super fat",
    "Make one sim super skinny",
    "Send your sim on a kissing spree, kiss as many Sims as you can",
    "Invite a neighbor over and lock them in a room. Keep them there as long as you like.",
    "Buy a Gnome",
    "Buy a potato. Make sure that potato has a place in your home and that nobody eats it.",
    "Invite some neighbors over and kill them, Make sure you keep all the urns or graves.",
    "Make one of your sims go to a community lot and hug as many Sims as they can find.",
    "Change all outfits to something new for one of your Sims",
    "Mount a fish (from a store or fished up) and hang it on the wall",
    "Oh no! Your kid traded in your [insert most expensive item here] for some magic beans! Delete the most expensive item in your house, and plant one bean plant.",
    "Make one of your sims go to a community lot and gossip with as many Sims as they can find",
    "Using testingcheatsenabled true shift click the mailbox, click force visitor and force a burglar to your lot",
    "Order a pizza, then have someone flirt with the pizza delivery man/woman.",
    "Copy one of your sims, then move the clone in.",
    "Switch all of your sims genders!",
    "Death Note: If you have a child or teenager, kill the person they have the lowest relationship with",
    "Swap any two sims' traits. You may change them back after three days.",
    "Male Bonding: Send your male sims off to do something together.",
    "Female Bonding: Send your female sims off to do something together.",
    "Night on the Town: Head out to a night club/bar/other drinking establishment of your choice and imbibe as much 'juice' as you can",
    "Movie night: gather the family for a movie",
    "Change just the everyday outfit for one sim",
    "Grab a friend and go cloud/star gazing",
    "Have your kid/teen invite friend(s) over for a sleepover",
    "Make an enemy"
    ];
    
const outputText = document.querySelector('#outputText');
    
function btnRandomizer() {

    const RandomSituation = Math.floor(Math.random() * situation.length);

    outputText.innerHTML = situation[RandomSituation];
}


